export const mockModules = [
  {
    moduleId: "fda-820-compliance",
    title: "FDA 820 Compliance",
    category: "Regulatory",
    version: "v1.0.3",
    downloads: 1245,
    creator: "0xA1B2...3C4D",
    description: "Build a plug-and-play FDA 820 quality system module, complete with electronic records compliance.",
    lastUpdated: "2025-06-15",
    tags: ["Regulatory", "Quality Control", "FDA"],
  },
  {
    moduleId: "part-cad-library",
    title: "Part CAD Library",
    category: "CAD",
    version: "v1.1.0",
    downloads: 845,
    creator: "0xB3C4...5D6E",
    description: "Library of parameterized CAD parts and BOMs for rapid deployment across factories.",
    lastUpdated: "2025-06-10",
    tags: ["CAD", "Design", "Manufacturing"],
  },
  {
    moduleId: "cnc-machining-sop",
    title: "CNC Machining SOP",
    category: "Production SOPs",
    version: "v0.9.8",
    downloads: 732,
    creator: "0xD4E5...6F7G",
    description: "Standardized operating procedures for CNC machining operations.",
    lastUpdated: "2025-06-05",
    tags: ["Production", "SOP", "Machining"],
  },
];
